FROM node:16-buster-slim

WORKDIR /opt/firebase

RUN apt-get -y update && apt-get -y install default-jre
RUN yarn global add firebase-tools

COPY .firebaserc .
COPY firebase.json .

RUN firebase setup:emulators:ui

CMD firebase --project=courseviz-405db emulators:start
